services:
  - type: web
    name: my-django-app
    env: python
    runtime: python3.11
    region: oregon

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: |
      gunicorn cimback.wsgi:application --bind 0.0.0.0:$PORT

    envVars:
      DJANGO_SETTINGS_MODULE: cimback.settings
      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "1"
